dbt_cfpb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../database/cfpb_complaints.duckdb'
      schema: main
      threads: 1
      # extensions: # list of extensions to load
      #   - httpfs
      #   - aws
      # settings:
      #   s3_endpoint: 'localhost:9000'
      #   s3_access_key_id: 'khai'
      #   s3_secret_access_key: 'khai2612'
      #   s3_region: 'us-east-1'
      #   s3_use_ssl: false
      #   s3_url_style: 'path'