name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: latest

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run ruff check
        run: uv run ruff check .

      - name: Run ruff format check
        run: uv run ruff --check format .

      - name: Validate dbt Charts
        run: |
          uv run dbt parse --project-dir cfpb_complaints --profiles-dir cfpb_complaints
          uv run dct validate --project-dir cfpb_complaints